name: Build and deploy

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      development_branch:
        description: Branch to deploy to development
        required: false
        type: string
        default: main

jobs:
  deploy-development:
    name: Deploy development
    strategy:
      fail-fast: false
      matrix:
        include:
          - checkout_ref: ${{ github.event_name == 'workflow_dispatch' && inputs.development_branch || github.ref_name }}
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      environment: development
      cluster: live
      ingress_colour: green
      aws_region: eu-west-2
      image_tag: latest
      slackbot_image_tag: slackbot_latest
      checkout_ref: ${{ matrix.checkout_ref }}
    secrets: inherit

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: deploy-development
    name: Deploy production
    uses: ./.github/workflows/reusable-build-and-deploy.yaml
    with:
      environment: production
      cluster: live
      ingress_colour: blue
      aws_region: eu-west-2
      image_tag: latest
      slackbot_image_tag: slackbot_latest
      checkout_ref: main
    secrets: inherit
